name: Deploy (production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- -c production

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.WIDGET_HOST }}
          username: ${{ secrets.GA_USER }}
          key: ${{ secrets.GA_USER_KEY }}
          target: ${{ secrets.PROD_DEPLOY_DIR }}
          source: dist/widget/*
          strip_components: 2
